# -*- coding: utf-8 -*-
"""Recoder

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T5DGNQJz9tmVhnoY5E7WhY9tiSP2QeR5
"""

from textwrap import wrap
import re
from difflib import SequenceMatcher

raw_input = str(input("What is your gene sequence? ")) #get user sequence

n= 3 #how many CHARS to chunk into

spliced = wrap(raw_input,n) #cuts it into thirds

medium= [i.replace('t',"T") for i in spliced]
splicer = [i.replace('T', 'U') for i in medium] #replaces t's with u's

for i in range(len(splicer)):
  splicer[i] = splicer[i].upper() #makes it uppercase
print(splicer)

optimized_3 = {'UUC': 'UUC', 'UUU':'UUC', 'UUA': 'UUC', 'UUG': 'UUC',
               'UCU': 'UCG', 'UCC': 'UCG', 'UCA':'UCG', 'UCG':'UCG',
               'UAU': 'UAC', 'UAC':'UAC', 'UAA':'UAC', 'UAG': 'UAC',
               'UGU': 'UGC', 'UGC': 'UGC', "UGA": 'UGC', 'UGG':'UGC',
               'CUU': 'CUG', 'CUC': 'CUG', 'CUG':'CUG', 'CUA':'CUG',
               'CCU':'CCG', 'CCC':'CCG', 'CAG':'CCG', 'CCA':'CCG',
               'CAG':'CAG','CAA':"CAG", 'CAC': 'CAG', 'CAU': 'CAG',
               'CGU': 'CGU', 'CGC': 'CGU', 'CGA': 'CGU', 'CGG': 'CGU',
               'AUG': 'AUG', 'AUU': 'AUG', 'AUC': 'AUG', 'AUA': 'AUG',
               'ACC': 'ACC', 'ACA': 'ACC', 'ACU': 'ACG', 'ACG':'ACC',
               'AAG': 'AAG', 'AAU': 'AAG', 'AAC':'AAG', 'AAA':'AAG',
               'AGC': 'AGC', 'AGU':'AGC', 'AGA': 'AGC', 'AGG': 'AGC',
               'GUG': 'GUG', 'GUA':'GUG', 'GUC':'GUG', 'GUU':'GUG',
               'GCC':'GCC', 'GCU': 'GCC', 'GCA':'GCC', 'GCG': 'GCC',
               'GAA': 'GAA', 'GAC':'GAA','GAG':'GAA','GAU':'GAA',
               'GGA': 'GGA', 'GGU':'GGA','GGC':'GGA', 'GGG':'GGA'}

res = [optimized_3.get(i,i) for i in splicer]
new_age = ' '.join(res)
new_age_2 = new_age.replace(" ", "")
new_age_3 = new_age_2.replace("U","T")
print("Your new DNA sequence is: " + new_age_3)

#similarity metric 


def similar(a, b):
  return SequenceMatcher(None, a, b).ratio()

sim_score = str(similar(raw_input.upper(), new_age_3))
print("The similarity between your old and new sequence is " +sim_score)

